### ISSUE TITLE
No Way to "Get" LoadBalancer resources in Another Stack

### ISSUE THREAD

**Issue by WonderPanda** [pulumi/pulumi-awsx#543] opened 2020-06-18 13:55 UTC
We are trying to split up our AWS resources across a couple different stacks so isolate things that change often versus resources that are more stable. We have a "core" Stack that defines things like our ECS Cluster, Network Load Balancer, VPC, etc.

Now we're trying to build a separate stack for deploying a Fargate Service onto the cluster but it appears that there's no exposed API for being able to retrieve a reference to the NLB or Target Groups/Listeners. Usually there's some kind of `get` method for being able to look up an already existing resource. Even the `awsx.ecs.Cluster` has the option to construct it using an existing ECS cluster resource passed in to the `cluster` arg which effectively then acts as a reference.

Is there no way to use Load Balancer resources in a multi stack scenario without falling back to just manually creating all of the AWS components ourselves and dropping awsx?

**Comment by leezen** [comment] 2020-06-18 16:06
Is this a duplicate of https://github.com/pulumi/pulumi-awsx/issues/535 or are you thinking of a different scenario?

**Comment by WonderPanda** [comment] 2020-06-18 16:12
They're related but I think this is a bit different. In this case I have a Load Balancer created with `awsx` so I'm not trying to adopt an existing LB. I just want the ability to reference the `awsx` resources wrappers inside of another Pulumi Stack so that I can have the ECS Cluster and Load Balancer in one stack and then reference those in another stack to set up a Fargate Service to consume those resources

**Comment by WonderPanda** [comment] 2020-06-18 17:43
Hmmm appreciate the insight. Rehydrating resources like what is outlined in 4133 definitely seems like it will be a welcome addition but right now I guess an equivalent to #535 might get us to where we need to be. I'd add that it seems like having the equivalent for `TargetGroups` and `Listeners` would be very helpful. In general there's an expectation that there is at least some way to get a reference to a resource in another stack using `.get` or an equivalent from it's Args object.

Any ideas on when #535 might be tackled?

**Comment by benmccann** [comment] 2020-07-18 03:04
This seems like a duplicate of https://github.com/pulumi/pulumi-aws/issues/824

Can you explain how #535 would help? I see that there's a pending PR for it https://github.com/pulumi/pulumi-awsx/pull/541

**Comment by benmccann** [comment] 2020-07-18 21:32
Answering my own question regarding #535, [the `aws.lb.LoadBalancer` has a `get` method](https://github.com/pulumi/pulumi-aws/blob/18293bd434b6763cff4a66dd5f43419e0dd5a5df/sdk/nodejs/lb/loadBalancer.ts#L84). So I think that you could `get` the `aws.lb.LoadBalancer` and then create an `awsx.lb.LoadBalancer` from it once #535 is checked in, which would be an absolutely enormous help

**Closed** 2020-07-27 20:44 UTC
