### ISSUE TITLE
Pulumi fails to 'plugin install resource awsx'

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-awsx#892] opened 2022-08-11 16:06 UTC
### What happened?

Cannot install awsx plugin for pulumi.

### Steps to reproduce

```
$ pulumi plugin install resource awsx
[resource plugin awsx-0.40.0] installing
warning: Error downloading plugin: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-awsx-v0.40.0-darwin-amd64.tar.gz
Will retry in 80ms [1/5]
warning: Error downloading plugin: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-awsx-v0.40.0-darwin-amd64.tar.gz
Will retry in 160ms [2/5]
warning: Error downloading plugin: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-awsx-v0.40.0-darwin-amd64.tar.gz
Will retry in 320ms [3/5]
warning: Error downloading plugin: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-awsx-v0.40.0-darwin-amd64.tar.gz
Will retry in 640ms [4/5]
warning: Error downloading plugin: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-awsx-v0.40.0-darwin-amd64.tar.gz
Will retry in 1.28s [5/5]
error: [resource plugin awsx-0.40.0] downloading from : failed to download plugin: awsx-0.40.0: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-awsx-v0.40.0-darwin-amd64.tar.gz
```

### Expected Behavior

Install works or a user-friendly error.

### Actual Behavior

Install errors out.

### Versions used

pulumi about                                 ~/schemas
CLI          
Version      3.37.2
Go Version   go1.17.12
Go Compiler  gc

Host     
OS       darwin
Version  11.6.7
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi

Pulumi locates its logs in /var/folders/mb/s1jx27m10t3082fqclpgytt80000gn/T/ by defaultwarning: Failed to get information about the plugin: failed to load language plugin : no language plugin 'pulumi-language-' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install language `
warning: Failed to get information about the project runtime: Unknown Language: : %!!(MISSING)w(<nil>)
warning: Failed to get information about the Pulumi program's plugins: Unknown Language: 
warning: Failed to get information about the current stack: no Pulumi.yaml project file found (searching upwards from ). If you have not created a project yet, use `pulumi new` to do so

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkodroff** [comment] 2022-08-11 21:40
AWSX < 1.0 is not mulit-lang and therefore requires no provider (resource) plugin.

AWSX >= 1.0 is multi-lang, and it's not released yet.

To install the beta plugin:

```
pulumi plugin install resource awsx 1.0.0-beta.10
```

Closing as by design.

**Closed** 2022-08-11 21:40 UTC
Labels: kind/bug, resolution/by-design
