### ISSUE TITLE
Master build broken

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-awsx#686] opened 2021-07-19 14:45 UTC
The last 4 master builds, and 11 of the last 15 master builds, have failed due to errors like the following:

```
Diagnostics:
1160
  aws:apigateway:VpcLink (containers7d5cd3e1):
1161
    error: deleting urn:pulumi:fargate-40124fb0::containers-fargate::aws:apigateway:x:API$aws:apigateway/vpcLink:VpcLink::containers7d5cd3e1: 1 error occurred:
1162
    	* error waiting for API Gateway VPC Link (v8vuub) deletion: couldn't find resource (21 retries)
1163
 
1164
  pulumi:pulumi:Stack (containers-fargate-fargate-40124fb0):
1165
    error: update failed
```

**Comment by leezen** [comment] 2021-07-20 22:52
This looks like potentially an upstream regression per https://github.com/hashicorp/terraform-provider-aws/issues/20247 and relatedly https://github.com/hashicorp/terraform-provider-aws/issues/20216

**Comment by stack72** [comment] 2022-02-03 21:00
We can close this out as this isn't an issue anymore

**Closed by stack72** 2022-02-03 21:00 UTC
Labels: kind/bug, resolution/fixed, awaiting-upstream
