### ISSUE TITLE
awsx.apigateway "The REST API doesn't contain any methods"

### ISSUE THREAD

**Issue by brandonbloom** [pulumi/pulumi-awsx#667] opened 2021-04-26 06:01 UTC
Occasional "The REST API doesn't contain any methods" error when using `awsx.apigateway`. This appears to be caused by a race condition between the construction of the integration method lambdas and the `Deployment` object.

Similar issue in another tool:
https://github.com/cloudtools/troposphere/issues/496

## Expected behavior

`new aws.apigateway.Deployment` should have a `dependsOn` that prevents this race condition.

## Steps to reproduce

I'm not able to reliably reproduce this issue. It seems to be triggered by subtle timing issues, but it happens with a pretty boring/small usage of awsx.apigateway. It might be possible to force this to happen by adding an arbitrary delay to some asynchronous input given to the integration method lambda function resources.

**Comment by komalali** [comment] 2021-04-27 17:33
Can you give us some code as an example of this "boring/small usage"? It'd be helpful to test and fix.

**Comment by brandonbloom** [comment] 2021-04-27 19:46
I was just following https://www.pulumi.com/docs/guides/crosswalk/aws/api-gateway/ – I am unable to reproduce this now though.

I tried the following, but it did not reproduce the issue:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";
import * as random from "@pulumi/random";

// Janky simple sleep resource mechanism.
const sleep = new random.RandomInteger("sleep", {
  min: 0,
  max: pulumi.output(10).apply(async (max) => {
    await new Promise((accept) => {
      setTimeout(accept, 10000);
    });
    return max;
  }),
});

const eventHandler = aws.lambda.createFunctionFromEventHandler(
  "handler",
  async (event) => {
    // This code runs in an AWS Lambda anytime `/` is hit.
    return {
      statusCode: 200,
      body: "Hello, API Gateway!",
    };
  },
  {
    // Slow down this event handler in the execution phase.
    dependsOn: sleep,
  }
);

// Define a new GET endpoint that just returns a 200 and "hello" in the body.
const api = new awsx.apigateway.API("example", {
  routes: [
    {
      path: "/",
      method: "GET",
      eventHandler,
    },
  ],
});

// Export the auto-generated API Gateway base URL.
export const url = api.url;
```

There must be some similar way to trigger it though by reasoning through the implementation more carefully.

**Comment by danielrbradley** [comment] 2022-05-16 14:01
Closing as not able to reproduce the issue. Can re-open if we can find a reliable reproduction.

**Closed by danielrbradley** 2022-05-16 14:01 UTC
Labels: kind/bug, resolution/no-repro
