### ISSUE TITLE
Name tag should not be applied to sub-resources of Vpc

### ISSUE THREAD

**Issue by peak-stephen** [pulumi/pulumi-awsx#985] opened 2023-02-01 19:54 UTC
### What happened?

I created a Vpc resource. Later I tried to set the `Name` tag of the VPC to a different value to change the display name in the AWS console, Pulumi tried to apply this to route tables and got stuck.

### Expected Behavior

The name of the VPC is updated.

### Steps to reproduce

1. Create a stack with a VPC. (I'm not sure if it needs to exist first or if this would happen on create as well).
2. Add `tags: { Name: "something-else" }` to the VPC. Run pulumi up
3. See that Pulumi wants to update every route table in the VPC to have the same name.
4. (optional) choose "yes" and observe that Pulumi will hang because you can't do that :)

### Output of `pulumi about`

CLI
Version      3.53.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME             VERSION
aws              5.16.2
awsx             1.0.1
command          0.7.0
docker           3.6.1
docker-buildkit  0.1.26
eks              1.0.1
kubernetes       3.23.1
python           unknown

Host
OS       ubuntu
Version  22.04
Arch     x86_64

8<--------------- snip ------------------

Dependencies:
NAME                    VERSION
pip                     22.3.1
pulumi-awsx             1.0.1
pulumi-command          0.7.0
pulumi-docker-buildkit  0.1.26
pulumi-eks              1.0.1
setuptools              66.1.1
typeguard               2.13.3
wheel                   0.38.4

### Additional context

I would guess that #939 introduced this behaviour.
#967 is about the lack of update to the VPC itself, and should probably be fixed at the same time.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment] 2023-02-01 23:59
Thanks for submitting this issue! It appears that you've identified the root cause and am attempting to submit a fix for it. We look forward to reviewing and submitting your PR!

**Comment by t0yv0** [comment] 2024-09-13 20:34
Fixed in https://github.com/pulumi/pulumi-awsx/pull/986 I believe.

**Closed** 2024-09-13 20:34 UTC
Labels: kind/bug, resolution/fixed, impact/regression
