### ISSUE TITLE
Tagging strategy is broken

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-awsx#938] opened 2022-11-09 19:28 UTC
### What happened?

When we specify tags on an `awsx.ec2.Vpc` - some of the resources don't get tags assigned to them.

This isn't ideal

### Steps to reproduce

Create a VPC

### Expected Behavior

All the resources that can be tagged, including RouteTables and igw etc, should get the same tags applied

### Actual Behavior

Only the VPC gets the tags applied

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jaxxstorm** [comment] 2022-11-09 19:34
related? #939 922

**Comment by danielrbradley** [comment] 2022-11-15 11:51
Yes, I believe this is a duplicate of #922 so closing. 

@jaxxstorm I think your PR #939 will resolve this - only has 1 minor adjustment required before merging.

**Closed by danielrbradley** 2022-11-15 11:51 UTC
Labels: kind/bug, resolution/duplicate
