### ISSUE TITLE
Creating vpc with custom provider causes missing secrets support error

### ISSUE THREAD

**Issue by SijmenHuizenga** [pulumi/pulumi-awsx#948] opened 2022-11-22 10:05 UTC
### What happened?

I'm trying to create an vpc in a different region then the primary pulumi region. Pulumi crashes with the error: `plugins that can construct components must support secrets`

### Steps to reproduce

```typescript
const myRegion = new aws.Provider("eu-central-1", {
  region: "eu-central-1",
});

const vpc = new awsx.ec2.Vpc("awsx-nodejs-default-args", undefined, { provider: myRegion });
```

```
pulumi up
```

### Expected Behavior

The vpc is created using the configured provider

### Actual Behavior

```
Diagnostics:
  pulumi:pulumi:Stack (infra-dev):
    error: Running program '/home/sijmen/ascento/arc_core/atmos/aws/infra' failed with an unhandled exception:
    Error: failed to register new resource vpc [awsx:ec2:Vpc]: 2 UNKNOWN: plugins that can construct components must support secrets
```

### Output of `pulumi about`

```
CLI
Version      3.47.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       arch
Version  "rolling"
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment] 2022-11-22 20:17
Possibly an issue with Pulumi Node SDK https://github.com/pulumi/pulumi/issues/11316

**Comment by t0yv0** [comment] 2022-11-22 20:20
Does it reproduce with Pulumi 3.43.1 and Pulumi Node SDK 3.43.1 ? From 11316 it seems that he issue has been introduced in versions after 3.34.1.

**Comment by t0yv0** [comment] 2022-11-22 20:37
I'm failing to reproduce with the following versions:

```
CLI          
Version      3.47.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.21.1
docker  3.6.1
nodejs  unknown

Host     
OS       darwin
Version  13.0.1
Arch     x86_64

This project is written in nodejs: executable='/Users/t0yv0/.nix-profile/bin/node' version='v16.16.0'

Current Stack: dev

TYPE                                                 URN
pulumi:pulumi:Stack                                  urn:pulumi:dev::i-948::pulumi:pulumi:Stack::i-948-dev
pulumi:providers:aws                                 urn:pulumi:dev::i-948::pulumi:providers:aws::eu-east-1
awsx:x:ec2:Vpc                                       urn:pulumi:dev::i-948::awsx:x:ec2:Vpc::awsx-nodejs-default-args
awsx:x:ec2:NatGateway                                urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:NatGateway::awsx-nodejs-default-args-1
aws:ec2/vpc:Vpc                                      urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$aws:ec2/vpc:Vpc::awsx-nodejs-default-args
awsx:x:ec2:Subnet                                    urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet::awsx-nodejs-default-args-public-0
awsx:x:ec2:Subnet                                    urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet::awsx-nodejs-default-args-private-0
awsx:x:ec2:Subnet                                    urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet::awsx-nodejs-default-args-public-1
awsx:x:ec2:Subnet                                    urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet::awsx-nodejs-default-args-private-1
awsx:x:ec2:NatGateway                                urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:NatGateway::awsx-nodejs-default-args-0
awsx:x:ec2:InternetGateway                           urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:InternetGateway::awsx-nodejs-default-args
aws:ec2/eip:Eip                                      urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:NatGateway$aws:ec2/eip:Eip::awsx-nodejs-default-args-1
aws:ec2/subnet:Subnet                                urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/subnet:Subnet::awsx-nodejs-default-args-public-0
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/routeTable:RouteTable::awsx-nodejs-default-args-public-0
aws:ec2/subnet:Subnet                                urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/subnet:Subnet::awsx-nodejs-default-args-private-0
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/routeTable:RouteTable::awsx-nodejs-default-args-private-0
aws:ec2/subnet:Subnet                                urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/subnet:Subnet::awsx-nodejs-default-args-public-1
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/routeTable:RouteTable::awsx-nodejs-default-args-public-1
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/routeTable:RouteTable::awsx-nodejs-default-args-private-1
aws:ec2/subnet:Subnet                                urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/subnet:Subnet::awsx-nodejs-default-args-private-1
aws:ec2/eip:Eip                                      urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:NatGateway$aws:ec2/eip:Eip::awsx-nodejs-default-args-0
aws:ec2/internetGateway:InternetGateway              urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:InternetGateway$aws:ec2/internetGateway:InternetGateway::awsx-nodejs-default-args
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/routeTableAssociation:RouteTableAssociation::awsx-nodejs-default-args-public-0
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/routeTableAssociation:RouteTableAssociation::awsx-nodejs-default-args-private-0
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/routeTableAssociation:RouteTableAssociation::awsx-nodejs-default-args-public-1
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/routeTableAssociation:RouteTableAssociation::awsx-nodejs-default-args-private-1
aws:ec2/route:Route                                  urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/route:Route::awsx-nodejs-default-args-public-1-ig
aws:ec2/route:Route                                  urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/route:Route::awsx-nodejs-default-args-public-0-ig
aws:ec2/natGateway:NatGateway                        urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:NatGateway$aws:ec2/natGateway:NatGateway::awsx-nodejs-default-args-0
aws:ec2/natGateway:NatGateway                        urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:NatGateway$aws:ec2/natGateway:NatGateway::awsx-nodejs-default-args-1
aws:ec2/route:Route                                  urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/route:Route::awsx-nodejs-default-args-private-0-nat-0
aws:ec2/route:Route                                  urn:pulumi:dev::i-948::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/route:Route::awsx-nodejs-default-args-private-1-nat-1


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi

Dependencies:
NAME            VERSION
@pulumi/awsx    0.40.1
@pulumi/pulumi  3.47.1
@types/node     14.18.33
@pulumi/aws     5.21.1

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/ by default
```

Had to modify the original program in TypeScript to use {} instead of undefined (rejected by type system):

```typescript

import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const myRegion = new aws.Provider("eu-east-1", {
  region: "us-east-1",
});

const vpc = new awsx.ec2.Vpc("awsx-nodejs-default-args", {}, { provider: myRegion });

```

**Comment by thutto** [comment] 2022-11-28 19:46
For me this error only happens on the awsx 1.0.0 stream ( 1.0.0-beta.11 to be exact ) 

I get the error on more than just VPC. It also happens on ECR, and ECS.

Example Error.
> Error: failed to register new resource node-app [awsx:ecr:Image]: 2 UNKNOWN: plugins that can construct components must support secrets

I did confirm it has to do with the use of a non default provider. I will try to get a full stack trace tonight with the (1.0.0 release), however I had to roll back to 0.40 for the time being.

**Comment by thutto** [comment] 2022-11-30 14:02
Testing the 1.0.0 release gives the same error.
```
Error: failed to register new resource test/test [awsx:ecr:Repository]: 2 UNKNOWN: plugins that can construct components must support secrets
        at Object.registerResource (node_modules/.pnpm/@pulumi+pulumi@3.48.0/node_modules/@pulumi/runtime/resource.ts:294:27)
        at new Resource (node_modules/.pnpm/@pulumi+pulumi@3.48.0/node_modules/@pulumi/resource.ts:402:13)
        at new ComponentResource (node_modules/.pnpm/@pulumi+pulumi@3.48.0/node_modules/@pulumi/resource.ts:895:9)
        at new Repository (node_modules/.pnpm/@pulumi+awsx@1.0.0/node_modules/@pulumi/ecr/repository.ts:68:9)
        at /infrastructure/modules/fargate/index.ts:58:18
        at Array.map (<anonymous>)
        at buildFargate (/infrastructure/modules/fargate/index.ts:14:58)
        at /infrastructure/index.ts:22:21
```

**Comment by justinvp** [comment] 2022-11-30 20:36
I'm still investigating why this error happens with the Node.js SDK when passing the provider via `{ provider: myRegion }` with AWSX 1.0...

In the meantime, I was able to get things working by passing the provider as: `{ providers: { aws: myRegion } }`.

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const myRegion = new aws.Provider("us-east-1", {
  region: "us-east-1",
});

const vpc = new awsx.ec2.Vpc("awsx-nodejs-default-args", {}, { providers: { aws: myRegion } });
```

**Comment by justinvp** [comment] 2022-12-01 00:39
Closing this as a dupe of https://github.com/pulumi/pulumi/issues/11316. Will continue the investigation there.

**Closed by justinvp** 2022-12-01 00:39 UTC
Labels: kind/bug, resolution/duplicate

**Comment by thutto** [comment] 2022-12-01 02:06
Thank you for the work around.
