### ISSUE TITLE
Can not create Fargate Task Definition with private image on ECR

### ISSUE THREAD

**Issue by lephuongbg** [pulumi/pulumi-awsx#1060] opened 2023-08-02 05:14 UTC
### What happened?

I'm trying to create a Fargate task definition, with a private ECR image. Running `pulumi up` keeps complaining the container image should not be null or empty

```
  aws:ecs:TaskDefinition (fms-backend-task-def-fgt-dev):
    error: 1 error occurred:
        * failed creating ECS Task Definition (fms-backend-task-def-fgt-dev-7caf8e31): ClientException: Container.image should not be null or empty
```

### Expected Behavior

Should be able to create a task definition with private ECR image

### Steps to reproduce

```typescript
// Create an ECR repository to hold the image
let repository = new awsx.ecr.Repository("backend-" + stackName);

// Build and push image to ECR
const image = new awsx.ecr.Image("image", {
  repositoryUrl: repository.url,
  path: ".",
  dockerfile: "./Dockerfile",
});

// Create an ECS cluster
let cluster = new aws.ecs.Cluster("cluster-" + stackName);

// Create task definition
let taskDefinition = new awsx.ecs.FargateTaskDefinition(
  "backend-task-def-" + stackName,
  {
    containers: {
      main: {
        command: [
          "celery"
        ],
        image: image.imageUri,
        memory: 256,
        cpu: 256,
      },
    },
  }
);
```

### Output of `pulumi about`

CLI          
Version      3.76.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.42.0
aws     5.0.0
awsx    1.0.2
awsx    1.0.0
docker  3.6.1
nodejs  unknown

Host     
OS       fedora
Version  38
Arch     x86_64

### Additional context

It only works if the image is set to a static string like `nginx:latest`. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment] 2023-08-02 11:20
Hi @lephuongbg sorry you're running into an issue - thanks for getting in touch.

I can see two potential places this issue could be coming from:
1. The output `image.imageUri` could be failing to resolve to a string. 
2. The input to `FargateTaskDefinition.containers[main].image` could be failing to wait correctly for the output to be resolved.

This seems somewhat dependent on exactly what's happening during the docker build and push - for which I can't see the details of your docker image. 

Some follow up questions to help us investigate:
1. Can you add `image.imageUri` as an output and confirm if it is a valid string value (and share a redacted version of the uri in the issue).
2. At the point of building the docker image and pushing it, is there any warnings or logs outputted? Please can you share any in this issue.
3. Please could you provide a minimal docker image which can be used to reproduce this issue?

Thanks!

**Comment by lephuongbg** [comment] 2023-08-03 10:18
> Can you add image.imageUri as an output and confirm if it is a valid string value (and share a redacted version of the uri in the issue).

> At the point of building the docker image and pushing it, is there any warnings or logs outputted? Please can you share any in this issue.

That was the first thing I do when I see the uri being null passing to the task definition. The output uri was valid, and the image was also uploaded to ECR succesfully.

> Please could you provide a minimal docker image which can be used to reproduce this issue?

```Dockerfile
FROM python:3.9

RUN groupadd saleor && useradd -g saleor saleor && mkdir /home/saleor && chown -R saleor:saleor /home/saleor

RUN apt-get update \
  && apt-get install -y \
  libcairo2 \
  libgdk-pixbuf2.0-0 \
  liblcms2-2 \
  libopenjp2-7 \
  libpango-1.0-0 \
  libpangocairo-1.0-0 \
  libssl3 \
  libtiff6 \
  libwebp7 \
  libxml2 \
  libpq5 \
  shared-mime-info \
  mime-support \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN echo 'image/webp webp' >> /etc/mime.types

WORKDIR /saleor
```

**Comment by danielrbradley** [comment] 2023-08-03 11:22
I've just run this locally (with minor update to the resource names) and it passes without error:

```typescript
// Create an ECR repository to hold the image
let repository = new awsx.ecr.Repository("backend");

// Build and push image to ECR
const image = new awsx.ecr.Image("image", {
  repositoryUrl: repository.url,
  path: ".",
  dockerfile: "./Dockerfile",
});

// Create an ECS cluster
let cluster = new aws.ecs.Cluster("cluster");

// Create task definition
let taskDefinition = new awsx.ecs.FargateTaskDefinition("backend-task-def", {
  containers: {
    main: {
      command: ["celery"],
      image: image.imageUri,
      memory: 256,
      cpu: 256,
    },
  },
});
```

```docker
FROM python:3.9

RUN groupadd saleor && useradd -g saleor saleor && mkdir /home/saleor && chown -R saleor:saleor /home/saleor

RUN apt-get update \
  && apt-get install -y \
  libcairo2 \
  libgdk-pixbuf2.0-0 \
  liblcms2-2 \
  libopenjp2-7 \
  libpango-1.0-0 \
  libpangocairo-1.0-0 \
  libssl3 \
  libtiff6 \
  libwebp7 \
  libxml2 \
  libpq5 \
  shared-mime-info \
  mime-support \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN echo 'image/webp webp' >> /etc/mime.types

WORKDIR /saleor
```

Dependencies:
```
Pulumi CLI v3.76.1
Node v18.9.0

NPM:
@pulumi/pulumi: 3.55.0
@pulumi/aws: 5.42.0
@pulumi/awsx: 1.0.2
@pulumi/docker: 3.6.1
```

**Comment by lephuongbg** [comment] 2023-08-03 13:52
It's node 16. I used nvm to installed node.

**Comment by thomas11** [comment] 2023-08-24 04:12
Closing this issue since we cannot reproduce. Feel free to re-open if necessary.

**Closed by thomas11** 2023-08-24 04:12 UTC
Labels: kind/bug, needs-repro, resolution/no-repro
