### ISSUE TITLE
`ServiceNetworkConfigurationArgs` is required but isn't exported

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-awsx#1032] opened 2023-06-27 22:01 UTC
### What happened?

Trying to create a Fargate service in a private subnet. I can't because to do that, I need to set `network_configuration` which requires `awsx.ecs.ServiceNetworkConfigurationArgs`

However, that isn't an actual property

### Expected Behavior

```
pulumi:pulumi:Stack (fargate_example_webapp-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/lbriggs/src/github/jaxxstorm/pulumi-examples/python/aws/fargate_postgres_webapp/deploy/__main__.py", line 34, in <module>
        network_configuration=awsx.ecs.ServiceNetworkConfigurationArgs(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: module 'pulumi_awsx.ecs' has no attribute 'ServiceNetworkConfigurationArgs'
```

### Steps to reproduce

```
webapp = awsx.ecs.FargateService(
    "example-webapp",
    cluster=cluster,
    network_configuration=awsx.ecs.ServiceNetworkConfigurationArgs(
        
    ),
    task_definition_args=awsx.ecs.FargateTaskDefinitionArgs(
        family="example-webapp",
        container=awsx.ecs.TaskDefinitionContainerDefinitionArgs(
            image=image.image_uri,
        )
    )
)
```

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jaxxstorm** [comment] 2023-06-27 22:05
This actually expects the network configuration args directly from `aws.ecs`

```
network_configuration=awsx.ecs.ServiceNetworkConfigurationArgs(
        aws.ecs.ServiceNetworkConfigurationArgs(
            subnets=vpc.private_subnet_ids,
        )
    ),
```

However that isn't immediately clear

**Comment by lukehoban** [comment] 2023-06-27 23:17
> This actually expects the network configuration args directly from aws.ecs

Yeah - that's right.  The types here appear to all be defined correctly - for example in:

https://github.com/pulumi/pulumi-awsx/blob/4a0b97b90336bae76b7a0c8d210cf271d2c8dc72/sdk/python/pulumi_awsx/ecs/fargate_service.py#L36

The assumption that this would be in `awsx` is likely for two reasons:
1. Most other argument types are in `awsx`
2. The IDE doesn't provide a fully qualified name

For (2), there's unfortunately not much we can do.  The IDEs typically present this in a low-fidelity way unfortunately, which can lead to confusion like this for any API.

For (1), it is important and intentional that we use whatever is available in AWS here - instead of inventing a new API at this layer.  The actual types do line up, so go-to-def does work here.

I expect that when we can make the design changes proposed in https://github.com/pulumi/pulumi/issues/11732, that will simplify this - since the type name won't need to be explicit - just the properties will need to be compatible.  But I'll close this one itself out as by design for now.

**Closed by lukehoban** 2023-06-27 23:17 UTC
Labels: kind/bug, needs-triage, resolution/by-design
