### ISSUE TITLE
Incorrect types in 1.0.1

### ISSUE THREAD

**Issue by nathan-knight** [pulumi/pulumi-awsx#972] opened 2023-01-06 21:23 UTC
### What happened?

I created an instance of `FargateTaskDefinition` which has `executionRole` and `taskRole`. The types say these should both be `pulumi.Output<pulumiAws.iam.Role | undefined>` but when I use them they are actually `pulumi.Output<string | undefined>` and the value they resolve to is the role name.

I would expect this to work given the types:
```typescript
const taskPolicy = new aws.iam.RolePolicy('policy-name', {
  policy: samplePolicy.apply((p) => p.json),
  role: taskDefinition.taskRole.apply(tr => tr!.name),
});
```
But it fails because `name` is undefined (not `tr`, `tr` is actually a string here if you log what its type is).

This also happens with `routeTables` in `awsx.ec2.Vpc`, instead of being `pulumi.Output<pulumiAws.ec2.RouteTable[]>` it is `pulumi.Output<string[]>` where the strings are the URNs of the route tables.

### Steps to reproduce

1. Use `@pulumi/awsx` v1.0.1 (I haven't tested other versions)
2. Try to use the fields mentioned above
3. It will build but you will get runtime errors due to values missing since you're trying to access fields on strings instead of the objects the types say you have

### Expected Behavior

You should get the objects themselves as the types suggest so you can access their properties.

### Actual Behavior

You get strings (role names for the roles, URNs for the route tables).

### Additional context

This probably affects other things as well, these are just the ones I happened to notice today when I was trying to migrate my code to the newest version (they ended up blocking me so I am using classic for now).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment] 2023-01-07 21:48
Hi @nathan-knight, thank you for reporting this! The output of `pulumi about` would be helpful to know which version of `@pulumi/pulumi` you have - or just look it up directly.

We'll investigate this further.

**Comment by nathan-knight** [comment] 2023-01-09 13:55
My CLI version is 3.51.0, the installed version for Node is 3.51.0 but the transitive dependency version is 3.48.0:
![image](https://user-images.githubusercontent.com/20479649/211324201-2d068b22-9eef-4400-8e8c-ed341362fdb4.png)

**Comment by justinvp** [comment] 2023-01-09 18:02
I wonder if multiple copies of `@pulumi/pulumi` are preventing the resource references from being deserialized as intended. Basically, having this fallback path run when a resource module registration for the resource can't be found: https://github.com/pulumi/pulumi/blob/2957b6b1b3f9c0d9f260bcd935b02a0b80765a67/sdk/nodejs/runtime/rpc.ts#L635-L639, causing it to return the string id of the resource, rather than an instance of the resource itself.

@nathan-knight, one thing worth trying is deleting your `yarn.lock` and `node_modules` dir, and re-running `yarn install` such that you have a single `@pulumi/pulumi`.

**Comment by nathan-knight** [comment] 2023-01-09 18:44
@justinvp 
I ran `yarn up -R @pulumi/pulumi` to bring all the versions to the latest version and that seems to have resolved it, thanks!

**Comment by guineveresaenger** [comment] 2023-01-09 19:55
I will close this issue for now - thanks all.

@nathan-knight feel free to reopen if this pops up again.

**Closed by guineveresaenger** 2023-01-09 19:55 UTC
Labels: kind/bug, resolution/by-design
