### ISSUE TITLE
Non-default `log_group` attribute of `awsx.ecs.FargateTaskDefinition` is `None`

### ISSUE THREAD

**Issue by WillDaSilva** [pulumi/pulumi-awsx#953] opened 2022-11-29 17:53 UTC
Context: https://github.com/pulumi/pulumi-awsx/issues/929#issuecomment-1331040221

```python
import pulumi_aws as aws
import pulumi_awsx as awsx

log_group = aws.cloudwatch.LogGroup("example-log-group")

task_def = awsx.ecs.FargateTaskDefinition(
    resource_name="task_def",
    log_group=awsx.awsx.DefaultLogGroupArgs(
        existing=awsx.awsx.ExistingLogGroupArgs(arn=log_group.arn)
    ),
    container=awsx.ecs.TaskDefinitionContainerDefinitionArgs(
        image="nginx:latest",
        cpu=256,
        memory=512,
        essential=True,
    ),
)
```

The `task_def.log_group` attribute should be the same `aws.cloudwatch.LogGroup` object as the `log_group` variable.

Instead, when the `log_group` parameter is supplied, the `task_def.log_group` attribute is set to `None`.

**Comment by lblackstone** [comment] 2022-11-30 00:32
FYI @justinvp since you looked at #929

**Comment by justinvp** [comment] 2022-11-30 00:41
@danielrbradley, correct me if I am wrong, but from looking at the schema and reading the implementation, this behavior appears to be intentional:

https://github.com/pulumi/pulumi-awsx/blob/43b8dabc0ec1e5187bf63e107bf06ee54021a1a7/awsx/ecs/fargateTaskDefinition.ts#L57-L58

https://github.com/pulumi/pulumi-awsx/blob/43b8dabc0ec1e5187bf63e107bf06ee54021a1a7/awsx/cloudwatch/logGroup.ts#L27-L40

https://github.com/pulumi/pulumi-awsx/blob/43b8dabc0ec1e5187bf63e107bf06ee54021a1a7/awsx/cloudwatch/logGroup.ts#L57-L90

If an existing log group is specified by `arn` or `name`, then `task_def.log_group` will not have a value, by-design.

In the case of the program above, we can't simply return `log_group` from `task_def.log_group`, because only `log_group.arn` was passed-in to the component (the component doesn't have the `log_group` instance).

**Comment by danielrbradley** [comment] 2022-11-30 10:14
Yes thank you @justinvp ... this is intended behaviour. We only return the resource if we've actually created it. Will close this out as by-design then.

There's likely some opportunity here to make this the docs a little clearer for this though.

**Closed by danielrbradley** 2022-11-30 10:14 UTC
Labels: kind/bug, language/python, resolution/by-design
