### ISSUE TITLE
apiKeySource not updated in awsx.classic.apigateway.API

### ISSUE THREAD

**Issue by albertocorrales** [pulumi/pulumi-awsx#1057] opened 2023-08-01 12:12 UTC
### What happened?

In order to implement tenant throttling on API Gateway, we had to update our APIs to set the setting `apiKeySource` to `AUTHORIZER`.

We were using the pulumi/awsx package to create our APIs and when we updated the setting `apiKeySource` we realized the change was not applied on AWS.

### Expected Behavior

When we update an existing API and we set the property `apiKeySource` as `AUTHORIZER`, this change should be applied on AWS.

### Steps to reproduce

Create an API as:

``` javascript
import * as awsx from "@pulumi/awsx";

let endpoint = new awsx.classic.apigateway.API("example", {
  routes: [
    {
      path: "/",
      method: "GET",

      eventHandler: async (event) => {
        // This code runs in an AWS Lambda and will be invoked any time `/` is hit.
        return {
          statusCode: 200,
          body: "hello",
        };
      },
    },
  ],
});
```

Update the `apiKeySource` as `AUTHORIZER`:

``` javascript
import * as awsx from "@pulumi/awsx";

let endpoint = new awsx.classic.apigateway.API("example", {
  apiKeySource: "AUTHORIZER",
  routes: [
    {
      path: "/",
      method: "GET",

      eventHandler: async (event) => {
        // This code runs in an AWS Lambda and will be invoked any time `/` is hit.
        return {
          statusCode: 200,
          body: "hello",
        };
      },
    },
  ],
});
```

### Output of `pulumi about`

```
CLI
Version      3.74.0  
Go Version   go1.20.5
Go Compiler  gc      

Plugins        
NAME    VERSION
aws     5.42.0 
awsx    1.0.2  
docker  3.6.1  
nodejs  unknown

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19045 Build 19045
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v18.13.0'

Current Stack: Alberto-Corrales/ApiGatewayAwsx/dev

TYPE                                               URN
pulumi:pulumi:Stack                                urn:pulumi:dev::ApiGatewayAwsx::pulumi:pulumi:Stack::ApiGatewayAwsx-dev
aws:apigateway:x:API                               urn:pulumi:dev::ApiGatewayAwsx::aws:apigateway:x:API::example
pulumi:providers:aws                               urn:pulumi:dev::ApiGatewayAwsx::pulumi:providers:aws::default_5_42_0
aws:iam/role:Role                                  urn:pulumi:dev::ApiGatewayAwsx::aws:apigateway:x:API$aws:iam/role:Role::example4c238266
aws:lambda/function:Function                       urn:pulumi:dev::ApiGatewayAwsx::aws:apigateway:x:API$aws:lambda/function:Function::example4c238266       
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:dev::ApiGatewayAwsx::aws:apigateway:x:API$aws:iam/rolePolicyAttachment:RolePolicyAttachment::example4c238266-b5aeb6b6
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:dev::ApiGatewayAwsx::aws:apigateway:x:API$aws:iam/rolePolicyAttachment:RolePolicyAttachment::example4c238266-e1a3786d
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:dev::ApiGatewayAwsx::aws:apigateway:x:API$aws:iam/rolePolicyAttachment:RolePolicyAttachment::example4c238266-1b4caae3
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:dev::ApiGatewayAwsx::aws:apigateway:x:API$aws:iam/rolePolicyAttachment:RolePolicyAttachment::example4c238266-74d12784
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:dev::ApiGatewayAwsx::aws:apigateway:x:API$aws:iam/rolePolicyAttachment:RolePolicyAttachment::example4c238266-4aaabb8e
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:dev::ApiGatewayAwsx::aws:apigateway:x:API$aws:iam/rolePolicyAttachment:RolePolicyAttachment::example4c238266-019020e7
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:dev::ApiGatewayAwsx::aws:apigateway:x:API$aws:iam/rolePolicyAttachment:RolePolicyAttachment::example4c238266-6c156834
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:dev::ApiGatewayAwsx::aws:apigateway:x:API$aws:iam/rolePolicyAttachment:RolePolicyAttachment::example4c238266-7cd09230
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:dev::ApiGatewayAwsx::aws:apigateway:x:API$aws:iam/rolePolicyAttachment:RolePolicyAttachment::example4c238266-a1de8170
aws:apigateway/restApi:RestApi                     urn:pulumi:dev::ApiGatewayAwsx::aws:apigateway:x:API$aws:apigateway/restApi:RestApi::example
aws:apigateway/deployment:Deployment               urn:pulumi:dev::ApiGatewayAwsx::aws:apigateway:x:API$aws:apigateway/deployment:Deployment::example       
aws:lambda/permission:Permission                   urn:pulumi:dev::ApiGatewayAwsx::aws:apigateway:x:API$aws:lambda/permission:Permission::example-fa520765  
aws:apigateway/stage:Stage                         urn:pulumi:dev::ApiGatewayAwsx::aws:apigateway:x:API$aws:apigateway/stage:Stage::example


Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/Alberto-Corrales
User           Alberto-Corrales
Organizations  Alberto-Corrales, fenergo_nebula

Pulumi locates its logs in C:\Users\ACORRA~1\AppData\Local\Temp by default
```

### Additional context

This issue is not happening if you create the resource is created originally with `apiKeySource` as `AUTHORIZER`. It only happens when we update an existing resource.

Apart from this, we have observed that when we update the setting `apiKeySource`, we need to redeploy the API to a particular stage, so API Gateway will apply the change properly.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment] 2023-08-01 14:07
When reproducing this issue locally, I'm seeing the diff show up correctly with the `apiKeySource` fed into the swagger spec:

![image](https://github.com/pulumi/pulumi-awsx/assets/331676/90f0eb45-1f2f-4d23-83a3-535ef588187c)

Looking at [the documentation for this field](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-api-key-source.html) it appears that the `AUTHORIZER` value is for use with a Lambda authorizer. There doesn't seem to be a Lambda authorizer specified in your example, so it's likely this change is being ignored by AWS and defaults back to `HEADER` if no Lambda authorizer is specified.

**Comment by albertocorrales** [comment] 2023-08-01 15:57
> When reproducing this issue locally, I'm seeing the diff show up correctly with the `apiKeySource` fed into the swagger spec:
> 
> ![image](https://user-images.githubusercontent.com/331676/257537132-90f0eb45-1f2f-4d23-83a3-535ef588187c.png)
> 
> Looking at [the documentation for this field](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-api-key-source.html) it appears that the `AUTHORIZER` value is for use with a Lambda authorizer. There doesn't seem to be a Lambda authorizer specified in your example, so it's likely this change is being ignored by AWS and defaults back to `HEADER` if no Lambda authorizer is specified.

Well, in that simple example there is no authorizer, but in the example it failed in my company we have the authorizer configured. So I guess there must be something else.

**Comment by danielrbradley** [comment] 2023-08-02 11:36
@albertocorrales interesting - the part I'm least clear on right now is how the API Key source relates to individual per-route authorizers in API Gateway.

If you are wanting to utilize authorizers more extensively, I'd suggest you might want to look at using the underlying AWS resources for API Gateway directly. There are a few known limitations with this abstraction - which is great for simple setups - but when adding in factors like authorization it lacks access to all underlying features.

**Comment by albertocorrales** [comment] 2023-08-03 07:03
Yeah, moving away of pulumi/awsx and start using pulumi/aws instead is in our plans. But at this point it is a change we need to plan and test properly, as it might be a breaking change for our existing APIs

**Comment by thomas11** [comment] 2023-09-28 07:00
I spent some more time on reproducing and narrowing down this issue, consulting with @danielrbradley as well. I tried three simple programs: the one from @albertocorrales above, the same but with a token authorizer, and the same but with a lambda authorizer. The behavior is the same for all of them, as described in the bug report.

As Daniel pointed out above, we see that Pulumi correctly updates the Swagger document. The only conclusion I can think of is therefore that AWS silently drops the changed `apiKeySource` from the Swagger spec on updates.

I also checked what request is made when you change the API key source in the UI (AWS console). It's a PATCH request against `/restapis/<myapi>` with no Swagger involved.

It looks like we'd need to rewrite this component to use standard REST resources instead of Swagger. When it was first written, Swagger might have been the only option. Such a rewrite would not only be considerable effort but would also very likely be a breaking change.

So, unfortunately, I don't have a quick fix for this at the moment. Going the pulumi-aws route as Daniel suggested might be the best option.


Sample program:
```typescript
import * as awsx from "@pulumi/awsx";

let endpoint = new awsx.classic.apigateway.API("example", {
  apiKeySource: "HEADER",
  routes: [
    {
      path: "/",
      method: "GET",

      eventHandler: async (event) => {
        // This code runs in an AWS Lambda and will be invoked any time `/` is hit.
        return {
          statusCode: 200,
          body: "hello",
        };
      },

      authorizers: [
        awsx.classic.apigateway.getTokenLambdaAuthorizer({
        // awsx.classic.apigateway.getRequestLambdaAuthorizer({
          handler: async (event) => {
            return {
              principalId: "user",
              policyDocument: {
                Version: "2012-10-17",
                Statement: [
                  {
                    Action: "execute-api:Invoke",
                    Effect: "Allow",
                    Resource: event.methodArn,
                  },
                ],
              },
            };
          },
          // queryParameters: ["token"],
        })
      ],
    },
  ],
});
```

**Comment by lukehoban** [comment] 2023-11-20 22:19
You can accomplish this via the `restApiArgs` escape hatch:

```ts
let endpoint = new awsx.classic.apigateway.API("example", {
    restApiArgs: {
        apiKeySource: "AUTHORIZER",
    },
    routes: [
      {
        path: "/",
        method: "GET",
  
        eventHandler: async (event) => {
          // This code runs in an AWS Lambda and will be invoked any time `/` is hit.
          return {
            statusCode: 200,
            body: "hello",
          };
        },
      },
    ],
  });
```

Perhaps counter-intuitively, AWS APIGateway manages this one property outside of the Swagger spec, so it must be sent to the `PutRestApi` call separately from the Swagger, even though it will get populated *into* the Swagger returned from the service.  This is likely an AWS bug, but it isn't blocking.

We can likely also fix this in the classic provider to do this automatically when provided directly to the constructor args instead of through Swagger.

**Closed** 2023-11-24 18:23 UTC
Labels: customer/feedback, kind/bug, customer/lighthouse
