### ISSUE TITLE
Intermittent failures in `fargateshort` example in CI

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi-awsx#391] opened 2019-08-21 19:11 UTC
My job hit what appears to be an intermittent failure, both during `up` and `destroy`:

During `up` (timeout waiting for VPCLink to become ready):
 
```
Invoke '/home/travis/.pulumi/bin/pulumi up --non-interactive --skip-preview' failed: exit status 255
Updating (moolumi/p-it-travis-job-fargatesho-a00fa1f0):

 +  pulumi:pulumi:Stack containers-fargate-p-it-travis-job-fargatesho-a00fa1f0 creating 
@ Updating.....
 +  pulumi:providers:aws prov creating 
 +  pulumi:providers:aws prov created 
 +  pulumi:pulumi:Stack containers-fargate-p-it-travis-job-fargatesho-a00fa1f0 creating read aws:ec2:Vpc default-vpc-043be661de8760bec
 +  awsx:x:ecs:Cluster testing creating 
 +  awsx:x:ec2:Vpc default-vpc-043be661de8760bec creating 
 +  awsx:lb:NetworkLoadBalancer nginx creating 
 +  awsx:x:ec2:SecurityGroup testing creating 
 +  aws:ecs:Cluster testing creating 
@ Updating....
 +  pulumi:pulumi:Stack containers-fargate-p-it-travis-job-fargatesho-a00fa1f0 creating read aws:ec2:Subnet default-vpc-043be661de8760bec-public-1
 +  awsx:x:ec2:Subnet default-vpc-043be661de8760bec-public-0 creating 
 +  awsx:x:ec2:Subnet default-vpc-043be661de8760bec-public-1 creating 
 +  pulumi:pulumi:Stack containers-fargate-p-it-travis-job-fargatesho-a00fa1f0 creating read aws:ec2:Subnet default-vpc-043be661de8760bec-public-0
 +  aws:ecs:Cluster testing created 
 +  pulumi:pulumi:Stack containers-fargate-p-it-travis-job-fargatesho-a00fa1f0 creating read aws:ec2:Subnet default-vpc-043be661de8760bec-public-1
 +  awsx:lb:NetworkListener nginx creating 
 +  pulumi:pulumi:Stack containers-fargate-p-it-travis-job-fargatesho-a00fa1f0 creating read aws:ec2:Vpc default-vpc-043be661de8760bec
 +  pulumi:pulumi:Stack containers-fargate-p-it-travis-job-fargatesho-a00fa1f0 creating read aws:ec2:Subnet default-vpc-043be661de8760bec-public-0
 +  awsx:lb:NetworkTargetGroup nginx creating 
 +  awsx:x:ec2:EgressSecurityGroupRule testing-egress creating 
 +  awsx:x:ec2:IngressSecurityGroupRule testing-ssh creating 
 +  awsx:x:ec2:IngressSecurityGroupRule testing-containers creating 
 +  awsx:x:ecs:FargateService nginx creating 
 +  aws:apigateway:x:API containers creating 
 +  awsx:x:ecs:FargateTaskDefinition nginx creating 
 +  aws:ec2:SecurityGroup testing creating 
 +  aws:lb:LoadBalancer nginx creating 
 +  aws:lb:TargetGroup nginx creating 
 +  aws:iam:Role containers679f3739 creating 
 +  aws:iam:Role nginx-execution creating 
 +  aws:iam:Role containers679f3739 created 
 +  aws:cloudwatch:LogGroup nginx creating 
 +  aws:iam:Role nginx-task creating 
 +  aws:iam:RolePolicyAttachment containers679f3739-32be53a2 creating 
 +  aws:iam:Role nginx-execution created 
 +  aws:ec2:SecurityGroup testing created 
 +  aws:iam:RolePolicyAttachment nginx-execution-9a42f520 creating 
 +  aws:lb:TargetGroup nginx created 
 +  aws:iam:Role nginx-task created 
 +  aws:iam:RolePolicyAttachment containers679f3739-32be53a2 created 
 +  aws:ec2:SecurityGroupRule testing-containers creating 
 +  aws:ec2:SecurityGroupRule testing-egress creating 
 +  aws:ec2:SecurityGroupRule testing-ssh creating 
 +  aws:iam:RolePolicyAttachment nginx-task-fd1a00e5 creating 
 +  aws:iam:RolePolicyAttachment nginx-task-32be53a2 creating 
 +  aws:iam:RolePolicyAttachment nginx-execution-9a42f520 created 
 +  aws:cloudwatch:LogGroup nginx created 
 +  aws:iam:RolePolicyAttachment nginx-task-fd1a00e5 created 
 +  aws:iam:RolePolicyAttachment nginx-task-32be53a2 created 
 +  aws:ec2:SecurityGroupRule testing-containers created 
 +  aws:ec2:SecurityGroupRule testing-egress created 
 +  aws:ec2:SecurityGroupRule testing-ssh created 
@ Updating...........
 +  aws:lb:LoadBalancer nginx created 
 +  aws:lb:Listener nginx creating 
 +  aws:apigateway:VpcLink containers7d5cd3e1 creating 
 +  aws:lb:Listener nginx created 
 +  aws:ecs:TaskDefinition nginx creating 
 +  aws:ecs:TaskDefinition nginx created 
 +  aws:lambda:Function containers679f3739 creating 
 +  aws:ecs:Service nginx creating 
 +  aws:lambda:Function containers679f3739 created 
@ Updating....
 +  aws:ecs:Service nginx created 
@ Updating..........................
 +  aws:apigateway:VpcLink containers7d5cd3e1 creating error: Plan apply failed: Error waiting for APIGateway Vpc Link status to be "AVAILABLE": timeout while waiting for state to become 'AVAILABLE' (last state: 'PENDING', timeout: 8m0s)
 +  aws:apigateway:VpcLink containers7d5cd3e1 **creating failed** error: Plan apply failed: Error waiting for APIGateway Vpc Link status to be "AVAILABLE": timeout while waiting for state to become 'AVAILABLE' (last state: 'PENDING', timeout: 8m0s)
 +  pulumi:pulumi:Stack containers-fargate-p-it-travis-job-fargatesho-a00fa1f0 creating error: update failed
 +  pulumi:pulumi:Stack containers-fargate-p-it-travis-job-fargatesho-a00fa1f0 **creating failed** 1 error
 
Diagnostics:
  aws:apigateway:VpcLink (containers7d5cd3e1):
    error: Plan apply failed: Error waiting for APIGateway Vpc Link status to be "AVAILABLE": timeout while waiting for state to become 'AVAILABLE' (last state: 'PENDING', timeout: 8m0s)
 
  pulumi:pulumi:Stack (containers-fargate-p-it-travis-job-fargatesho-a00fa1f0):
    error: update failed
 
Resources:
    + 35 created

Duration: 11m50s
```

During `destroy` (I assume there is some race here, since the log shows that the service was deleted):

```
Invoke '/home/travis/.pulumi/bin/pulumi destroy --non-interactive --skip-preview' failed: exit status 255
Destroying (moolumi/p-it-travis-job-fargatesho-a00fa1f0):

 -  aws:ecs:Service nginx deleting 
@ Destroying.....................
 -  aws:ecs:Service nginx deleted 
 -  aws:ecs:TaskDefinition nginx deleting 
 -  aws:ecs:TaskDefinition nginx deleted 
 -  aws:lb:Listener nginx deleting 
 -  aws:ec2:SecurityGroupRule testing-ssh deleting 
 -  aws:ec2:SecurityGroupRule testing-containers deleting 
 -  aws:ec2:SecurityGroupRule testing-egress deleting 
 -  aws:lb:Listener nginx deleted 
 -  aws:ec2:SecurityGroupRule testing-ssh deleted 
 -  aws:ec2:SecurityGroupRule testing-containers deleted 
@ Destroying....
 -  aws:ec2:SecurityGroupRule testing-egress deleted 
 -  awsx:x:ec2:EgressSecurityGroupRule testing-egress deleting 
 -  aws:iam:RolePolicyAttachment containers679f3739-32be53a2 deleting 
 -  awsx:x:ec2:IngressSecurityGroupRule testing-containers deleting 
 -  aws:lb:TargetGroup nginx deleting 
 -  aws:ec2:SecurityGroup testing deleting 
 -  aws:iam:RolePolicyAttachment nginx-task-32be53a2 deleting 
 -  aws:lb:LoadBalancer nginx deleting 
 -  aws:lambda:Function containers679f3739 deleting 
 -  aws:iam:RolePolicyAttachment nginx-execution-9a42f520 deleting 
 -  awsx:x:ec2:IngressSecurityGroupRule testing-ssh deleting 
 -  aws:iam:RolePolicyAttachment nginx-task-fd1a00e5 deleting 
 -  aws:iam:RolePolicyAttachment containers679f3739-32be53a2 deleted 
 -  aws:lb:TargetGroup nginx deleted 
 -  aws:iam:RolePolicyAttachment nginx-task-32be53a2 deleted 
 -  aws:lb:LoadBalancer nginx deleting error: Plan apply failed: deleting urn:pulumi:p-it-travis-job-fargatesho-a00fa1f0::containers-fargate::awsx:lb:NetworkLoadBalancer$aws:lb/loadBalancer:LoadBalancer::nginx: Error deleting LB: ResourceInUse: Load balancer 'arn:aws:elasticloadbalancing:us-west-2:894850187425:loadbalancer/net/nginx-7105fc0/41d1bc7a5fadaaa7' cannot be deleted because it is currently associated with another service
 -  aws:lb:LoadBalancer nginx **deleting failed** error: Plan apply failed: deleting urn:pulumi:p-it-travis-job-fargatesho-a00fa1f0::containers-fargate::awsx:lb:NetworkLoadBalancer$aws:lb/loadBalancer:LoadBalancer::nginx: Error deleting LB: ResourceInUse: Load balancer 'arn:aws:elasticloadbalancing:us-west-2:894850187425:loadbalancer/net/nginx-7105fc0/41d1bc7a5fadaaa7' cannot be deleted because it is currently associated with another service
 -  aws:lambda:Function containers679f3739 deleted 
 -  aws:ec2:SecurityGroup testing deleted 
 -  aws:iam:RolePolicyAttachment nginx-execution-9a42f520 deleted 
 -  aws:iam:RolePolicyAttachment nginx-task-fd1a00e5 deleted 
    pulumi:pulumi:Stack containers-fargate-p-it-travis-job-fargatesho-a00fa1f0  error: update failed
    pulumi:pulumi:Stack containers-fargate-p-it-travis-job-fargatesho-a00fa1f0 **failed** 1 error
 -  awsx:x:ec2:EgressSecurityGroupRule testing-egress deleted 
 -  awsx:x:ec2:IngressSecurityGroupRule testing-containers deleted 
 -  awsx:x:ec2:IngressSecurityGroupRule testing-ssh deleted 
 
Diagnostics:
  aws:lb:LoadBalancer (nginx):
    error: Plan apply failed: deleting urn:pulumi:p-it-travis-job-fargatesho-a00fa1f0::containers-fargate::awsx:lb:NetworkLoadBalancer$aws:lb/loadBalancer:LoadBalancer::nginx: Error deleting LB: ResourceInUse: Load balancer 'arn:aws:elasticloadbalancing:us-west-2:894850187425:loadbalancer/net/nginx-7105fc0/41d1bc7a5fadaaa7' cannot be deleted because it is currently associated with another service
    	status code: 400, request id: 14eaaf4f-c446-11e9-ab6c-e9906ba88bfd
 
  pulumi:pulumi:Stack (containers-fargate-p-it-travis-job-fargatesho-a00fa1f0):
    error: update failed
 
Resources:
    - 16 deleted

Duration: 6m24s
```

**Comment by skoschik** [comment] 2019-09-09 16:41
I believe this is an issue with the Terraform AWS provider and VPC links to API Gateway.
When using terraform and aws provider alone (without pulumi)  this issue with VPC links to API Gateway come up for me.  I cannot create a VPC link to API Gateway with the suggested config from [here](https://www.terraform.io/docs/providers/aws/r/api_gateway_integration.html#vpc-link): 

I'm trying to find the cause before opening and issue on the terraform aws provider github.  But i believe that's where the issue arises.

**Comment by lukehoban** [comment] 2020-07-24 00:39
We haven't seen this again recently - so closing out for now.

**Closed by lukehoban** 2020-07-24 00:39 UTC
