### ISSUE TITLE
ApiGateway does not create folders when uploading local website to S3

### ISSUE THREAD

**Issue by mgreuel** [pulumi/pulumi-awsx#574] opened 2020-09-10 18:22 UTC
When I upload a local static site with subfolders via awsx.apigateway.API -> localPath, the files are uploaded to S3 using '\' instead of '/' and therefor does not create a folder structure in the bucket.

I'm on Windows, so maybe the local path separator is used?!

![S3](https://user-images.githubusercontent.com/1005040/92780295-3b664b80-f3a3-11ea-9f1e-f11b40971816.png)
![local](https://user-images.githubusercontent.com/1005040/92780300-3dc8a580-f3a3-11ea-92db-74bac3d863d8.png)

**Comment by leezen** [comment] 2020-09-10 19:16
Closing as a dupe of https://github.com/pulumi/pulumi-awsx/issues/529

**Closed by leezen** 2020-09-10 19:16 UTC
