### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by universam1** [pulumi/pulumi-awsx#672] opened 2021-05-12 12:13 UTC
The `go.mod` module suggests this library is intended for Golang usage - is that support existing or planned?

Thank you!

**Comment by lblackstone** [comment] 2021-05-13 17:37
I'm going to close this as a dupe of https://github.com/pulumi/pulumi-awsx/issues/308

Support is planned as a multi-lang Package in the future.

**Closed by lblackstone** 2021-05-13 17:37 UTC
Labels: kind/enhancement, resolution/duplicate
