### ISSUE TITLE
The `createListener` does not work on `awsx.lb.ApplicationLoadBalancer` when imported in another stack.

### ISSUE THREAD

**Issue by sverch** [pulumi/pulumi-awsx#1138] opened 2023-10-31 14:18 UTC
### What happened?

In one stack, I can call `alb.createListener` no problem. But if I instead export that `awsx.lb.ApplicationLoadbalancer` object and import it into another stack, I get `error: TypeError: alb.createListener is not a function`.

### Example

1. From one stack, create a new `awsx.lb.ApplicationLoadBalancer`.
2. From another stack, import it from the first stack's output.
3. Try to call `alb.createListener`.

### Output of `pulumi about`

```
 $ pulumi about
CLI          
Version      3.86.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/home/user/.nvm/versions/node/v20.7.0/bin/node' version='v20.7.0'

Backend        
Name           pulumi.com
URL            ...
User           ...
Organizations  ...
Token type     personal
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment] 2023-11-01 06:18
@sverch Could you please share a code snippet, showing the way you export the ALB and then import it in another stack? Thank you!

**Comment by sverch** [comment] 2023-11-19 11:32
Hi @mikhailshilkov, sorry for the delay. Here's roughly what it looks like:

From one stack:

```
const alb = new awsx.lb.ApplicationLoadBalancer(
    name,
    {
      idleTimeout: 30,
      securityGroups: [albSecurityGroup.id],
      subnets: vpc.publicSubnetIds,
      vpc,
    },
    { protect, provider }
  );
  return alb;
}

export { exportedAlb }
```

From the other stack:

```
const albOutput: Promise<awsx.lb.ApplicationLoadBalancer> = originalStack.requireOutputValue("exportedAlb");

async function createListener() {
    const alb = await albOutput;
    const listener = alb.createListener(name, { ...other args... });
    ...
}
createListener();
```

Unfortunately I moved on and just called `createListener` from the stack it was created, and don't have the original failing case anymore. If you can't reproduce this or think this might just be something I did wrong, feel free to close.

**Comment by mikhailshilkov** [comment] 2023-11-23 13:00
Yes, I think this is expected behavior. You can't really `requireOutputValue` an object and then call a function on it. TypeScript allows you to do so, but what you get is not an object of an original shape with the function definitions.

Since you have a workaround, I'll go ahead and close the issue.

**Closed by mikhailshilkov** 2023-11-23 13:00 UTC
Labels: kind/bug, resolution/by-design

**Comment by sverch** [comment] 2023-11-25 13:11
@mikhailshilkov Oh, that's good to know, thank you! So if we use `requireOutput` instead the function should exist and work as it does in the original stack?
